import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin:
https://github.com/tbloth/obsghsync
*/
(function () {
  var g = typeof globalThis !== "undefined" ? globalThis : window;
  if (typeof g.global === "undefined") g.global = g;
  if (typeof g.process === "undefined") {
    g.process = { env: {}, platform: "browser", browser: true, version: "", domain: null, nextTick: function (cb) { Promise.resolve().then(cb); } };
  }
})();
`;

const prod = process.argv[2] === "production";

// Keep Node built-ins external EXCEPT polyfillable ones we bundle for mobile
// (iPadOS/iOS have no Node runtime, so `require("buffer")` would fail at load).
const bundledPolyfills = new Set(["buffer"]);
const externalBuiltins = builtins.filter((m) => !bundledPolyfills.has(m));

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...externalBuiltins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    global: "window",
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
